packages:
  - bundles/*
  - demo/*
  - effects/*
  - engine
  - interactions/*
  - interactions/*/*
  - wrappers/*
  - wrappers/inferno-hooks
  - templates/*
  - palettes/*/*
  - paths/*
  - plugins/*
  - plugins/colors/*
  - plugins/easings/*
  - plugins/emittersShapes/*
  - plugins/exports/*
  - presets/*
  - shapes/*
  - updaters/*
  - utils/*
  - websites/*
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tsparticles/engine': true
  canvas: true
  core-js: true
  core-js-bundle: true
  core-js-pure: true
  electron: true
  esbuild: true
  fsevents: true
  inferno: true
  lmdb: true
  msgpackr-extract: true
  nuxt: true
  nx: true
  puppeteer: true
  sharp: true
  svelte-preprocess: true
  unrs-resolver: true
linkWorkspacePackages: deep

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - "@tsparticles/engine"
  - canvas
  - core-js
  - core-js-pure
  - electron
  - esbuild
  - fsevents
  - nuxt
  - nx
  - sharp
  - unrs-resolver
