packages:
  - 'bundles/*'
  - 'demo/*'
  - 'engine'
  - 'interactions/*'
  - 'interactions/external/*'
  - 'interactions/particles/*'
  - 'move/*'
  - 'paths/*'
  - 'plugins/*'
  - 'plugins/easings/*'
  - 'plugins/exports/*'
  - 'shapes/*'
  - 'updaters/*'
  - 'utils/*'
  - 'websites/*'
