"use strict";

module.exports = function (environment) {
  const ENV = {
    // Use the package name (including scope) so the runtime module prefix
    // matches the module ids generated by the build (they are scoped
    // under @tsparticles/ember-demo). This avoids runtime loader mismatches
    // where the boot code requires "ember-demo/app" but modules are defined
    // as "@tsparticles/ember-demo/app".
    modulePrefix: "@tsparticles/ember-demo",
    environment,
    rootURL: "/",
    locationType: "history",
    EmberENV: {
      FEATURES: {},
      EXTEND_PROTOTYPES: false,
    },
    APP: {},
  };

  if (environment === "test") {
    ENV.locationType = "none";
    ENV.APP.rootElement = "#ember-testing";
    ENV.APP.autoboot = false;
  }

  return ENV;
};
