import Application from "@ember/application";
import Resolver from "ember-resolver";
import loadInitializers from "ember-load-initializers";
// The environment module is emitted under the package namespace in the
// compiled output (e.g. @tsparticles/ember-demo/config/environment). Import
// using the package-scoped name so runtime module ids match the AMD/ESM
// modules generated by the build.
import config from "@tsparticles/ember-demo/config/environment";

export default class App extends Application {
  modulePrefix = config.modulePrefix;
  podModulePrefix = config.podModulePrefix;
  Resolver = Resolver;
}

loadInitializers(App, config.modulePrefix);
