import { defineConfig } from "vitepress";

const base = process.env.VITEPRESS_BASE ?? "/";
const hostname = "https://particles.js.org";

export default defineConfig({
  title: "tsParticles",
  description: "Modern particle animations for the web",
  lang: "en-US",
  cleanUrls: true,
  lastUpdated: true,
  base,
  vite: {
    envDir: "..",
  },
  sitemap: {
    hostname,
  },
  head: [
    ["meta", { name: "theme-color", content: "#0b1020" }],
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:title", content: "tsParticles" }],
    ["meta", { property: "og:description", content: "TypeScript particle engine for websites and apps" }],
  ],
  themeConfig: {
    logo: "https://particles.js.org/tsParticles-64.png",
    socialLinks: [{ icon: "github", link: "https://github.com/tsparticles/tsparticles" }],
    nav: [
      { text: "Start", link: "/guide/getting-started" },
      { text: "Playground", link: "/playground/" },
      { text: "Demos", link: "/demos/" },
      { text: "Wrappers", link: "/guide/wrappers" },
      { text: "Options", link: "/options/" },
      { text: "Releases", link: "/releases/" },
    ],
    sidebar: {
      "/guide/wrappers": [
        {
          text: "Guides",
          items: [
            { text: "Wrappers Overview", link: "/guide/wrappers" },
            { text: "Framework Integrations", link: "/guide/frameworks" },
          ],
        },
        {
          text: "Wrappers",
          items: [
            { text: "Angular", link: "/guide/wrappers-angular" },
            { text: "React", link: "/guide/wrappers-react" },
            { text: "Svelte", link: "/guide/wrappers-svelte" },
            { text: "Vue", link: "/guide/wrappers-vue3" },
            { text: "Next.js", link: "/guide/wrappers-nextjs" },
            { text: "Nuxt 2", link: "/guide/wrappers-nuxt2" },
            { text: "Nuxt 3", link: "/guide/wrappers-nuxt3" },
            { text: "Nuxt 4", link: "/guide/wrappers-nuxt4" },
            { text: "Vue 2", link: "/guide/wrappers-vue2" },
            { text: "Vue 3", link: "/guide/wrappers-vue3" },
            { text: "Angular Confetti", link: "/guide/wrappers-angular-confetti" },
            { text: "Angular Fireworks", link: "/guide/wrappers-angular-fireworks" },
            { text: "Astro", link: "/guide/wrappers-astro" },
            { text: "Ember", link: "/guide/wrappers-ember" },
            { text: "Inferno", link: "/guide/wrappers-inferno" },
            { text: "jQuery", link: "/guide/wrappers-jquery" },
            { text: "Lit", link: "/guide/wrappers-lit" },
            { text: "Preact", link: "/guide/wrappers-preact" },
            { text: "Qwik", link: "/guide/wrappers-qwik" },
            { text: "Riot", link: "/guide/wrappers-riot" },
            { text: "Solid", link: "/guide/wrappers-solid" },
            { text: "Web Components", link: "/guide/wrappers-webcomponents" },
            { text: "WordPress", link: "/guide/wrappers-wordpress" },
          ],
        },
      ],
      "/guide/": [
        {
          text: "Guide",
          items: [
            { text: "Getting Started", link: "/guide/getting-started" },
            { text: "Installation", link: "/guide/installation" },
            { text: "Framework Integrations", link: "/guide/frameworks" },
            { text: "Color Formats", link: "/guide/color-formats" },
            { text: "Container Lifecycle", link: "/guide/container-lifecycle" },
            { text: "Plugins & Customization", link: "/guide/plugins-customization" },
            { text: "Templates & Resources", link: "/guide/templates-resources" },
            { text: "Video Tutorials", link: "/guide/video-tutorials" },
            { text: "Dependency Graph", link: "/guide/dependency-graph" },
          ],
        },
      ],
      "/guide/wrappers-": [
        {
          text: "Guides",
          items: [
            { text: "Wrappers Overview", link: "/guide/wrappers" },
            { text: "Framework Integrations", link: "/guide/frameworks" },
          ],
        },
        {
          text: "Wrappers",
          items: [
            { text: "Angular", link: "/guide/wrappers-angular" },
            { text: "React", link: "/guide/wrappers-react" },
            { text: "Svelte", link: "/guide/wrappers-svelte" },
            { text: "Vue", link: "/guide/wrappers-vue3" },
            { text: "Next.js", link: "/guide/wrappers-nextjs" },
            { text: "Nuxt 2", link: "/guide/wrappers-nuxt2" },
            { text: "Nuxt 3", link: "/guide/wrappers-nuxt3" },
            { text: "Nuxt 4", link: "/guide/wrappers-nuxt4" },
            { text: "Vue 2", link: "/guide/wrappers-vue2" },
            { text: "Vue 3", link: "/guide/wrappers-vue3" },
            { text: "Angular Confetti", link: "/guide/wrappers-angular-confetti" },
            { text: "Angular Fireworks", link: "/guide/wrappers-angular-fireworks" },
            { text: "Astro", link: "/guide/wrappers-astro" },
            { text: "Ember", link: "/guide/wrappers-ember" },
            { text: "Inferno", link: "/guide/wrappers-inferno" },
            { text: "jQuery", link: "/guide/wrappers-jquery" },
            { text: "Lit", link: "/guide/wrappers-lit" },
            { text: "Preact", link: "/guide/wrappers-preact" },
            { text: "Qwik", link: "/guide/wrappers-qwik" },
            { text: "Riot", link: "/guide/wrappers-riot" },
            { text: "Solid", link: "/guide/wrappers-solid" },
            { text: "Web Components", link: "/guide/wrappers-webcomponents" },
            { text: "WordPress", link: "/guide/wrappers-wordpress" },
          ],
        },
      ],
      "/playground/": [
        {
          text: "Playground",
          items: [
            { text: "Overview", link: "/playground/" },
            { text: "Bundles", link: "/playground/bundles" },
            { text: "Configs", link: "/playground/configs" },
            { text: "Palettes", link: "/playground/palettes" },
            { text: "Presets", link: "/playground/presets" },
          ],
        },
      ],
      "/demos/": [
        {
          text: "Demos",
          items: [
            { text: "Ready-to-Use", link: "/demos/" },
            { text: "Presets Catalog", link: "/demos/presets" },
            { text: "Palettes Catalog", link: "/demos/palettes" },
            { text: "Ambient", link: "/demos/recipes/ambient" },
            { text: "Big Circles", link: "/demos/recipes/big-circles" },
            { text: "Bubbles", link: "/demos/recipes/bubbles" },
            { text: "Confetti", link: "/demos/recipes/confetti" },
            { text: "Confetti Cannon", link: "/demos/recipes/confetti-cannon" },
            { text: "Confetti Explosions", link: "/demos/recipes/confetti-explosions" },
            { text: "Confetti Falling", link: "/demos/recipes/confetti-falling" },
            { text: "Confetti Parade", link: "/demos/recipes/confetti-parade" },
            { text: "Fire", link: "/demos/recipes/fire" },
            { text: "Firefly", link: "/demos/recipes/firefly" },
            { text: "Fireworks", link: "/demos/recipes/fireworks" },
            { text: "Fountain", link: "/demos/recipes/fountain" },
            { text: "Hyperspace", link: "/demos/recipes/hyperspace" },
            { text: "Links", link: "/demos/recipes/links" },
            { text: "Matrix", link: "/demos/recipes/matrix" },
            { text: "Sea Anemone", link: "/demos/recipes/sea-anemone" },
            { text: "Snow", link: "/demos/recipes/snow" },
            { text: "Squares", link: "/demos/recipes/squares" },
            { text: "Stars", link: "/demos/recipes/stars" },
            { text: "Triangles", link: "/demos/recipes/triangles" },
          ],
        },
      ],
      "/options/": [
        {
          text: "Options",
          items: [
            { text: "Options Reference", link: "/options/" },
            { text: "Background & Canvas", link: "/options/background" },
            { text: "Background Mask", link: "/options/background-mask" },
            { text: "Full Screen", link: "/options/fullscreen" },
            { text: "Motion", link: "/options/motion" },
            { text: "Manual Particles", link: "/options/manual-particles" },
            { text: "Themes", link: "/options/themes" },
            { text: "Particles", link: "/options/particles" },
            { text: "Particles Number", link: "/options/particles-number" },
            { text: "Particles Move", link: "/options/particles-move" },
            { text: "Particles Links", link: "/options/particles-links" },
            { text: "Particles Palette", link: "/options/particles-palette" },
            { text: "Particles Shape", link: "/options/particles-shape" },
            { text: "Particles Bounce", link: "/options/particles-bounce" },
            { text: "Particles Collisions", link: "/options/particles-collisions" },
            { text: "Particles Color", link: "/options/particles-color" },
            { text: "Particles Destroy", link: "/options/particles-destroy" },
            { text: "Particles Group", link: "/options/particles-group" },
            { text: "Particles Life", link: "/options/particles-life" },
            { text: "Particles Opacity", link: "/options/particles-opacity" },
            { text: "Particles Orbit", link: "/options/particles-orbit" },
            { text: "Particles Repulse", link: "/options/particles-repulse" },
            { text: "Particles Roll", link: "/options/particles-roll" },
            { text: "Particles Rotate", link: "/options/particles-rotate" },
            { text: "Particles Shadow", link: "/options/particles-shadow" },
            { text: "Particles Size", link: "/options/particles-size" },
            { text: "Particles Stroke", link: "/options/particles-stroke" },
            { text: "Particles Tilt", link: "/options/particles-tilt" },
            { text: "Particles Twinkle", link: "/options/particles-twinkle" },
            { text: "Particles Wobble", link: "/options/particles-wobble" },
            { text: "Particles ZIndex", link: "/options/particles-zindex" },
            { text: "Interactivity", link: "/options/interactivity" },
            { text: "Interactivity Click", link: "/options/interactivity-click" },
            { text: "Interactivity Hover", link: "/options/interactivity-hover" },
            { text: "Interactivity Div", link: "/options/interactivity-div" },
            { text: "Interactivity Events", link: "/options/interactivity-events" },
            { text: "Interactivity Modes", link: "/options/interactivity-modes" },
            { text: "Plugin: Absorbers", link: "/options/plugin-absorbers" },
            { text: "Plugin: Emitters", link: "/options/plugin-emitters" },
            { text: "Plugin: Infection", link: "/options/plugin-infection" },
            { text: "Plugin: Polygon Mask", link: "/options/plugin-polygon-mask" },
            { text: "Performance Guide", link: "/options/performance" },
          ],
        },
      ],
      "/migration/": [{ text: "Migration", items: [{ text: "Compatibility & Migrations", link: "/migration/" }] }],
      "/releases/": [{ text: "Releases", items: [{ text: "Versioning & Release", link: "/releases/" }] }],
    },
    search: {
      provider: "local",
    },
    footer: {
      message:
        'Released under MIT License. <a href="/cookie-policy">Cookie Policy</a> · <a href="/privacy-policy">Privacy Policy</a>',
      copyright: "Copyright © 2026 Matteo Bruni",
    },
  },
});
